using Display;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace problem12
{
    class Program
    {
        static void Main(string[] args)
        {

            DisplayScreen pb12display = new DisplayScreen();
            pb12display.ProblemTitle = "Problem 12";
            pb12display.ProblemHeader = "Highly divisible triangular number";
            pb12display.Description = "The sequence of triangle numbers is generated by adding the natural numbers.\n So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.\n The first ten terms would be:\n1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...\nLet us list the factors of the first seven triangle numbers:\n1: 1\n3: 1,3\n6: 1,2,3,6\n10: 1,2,5,10\n15: 1,3,5,15\n21: 1,3,7,21\n28: 1,2,4,7,14,28\nWe can see that 28 is the first triangle number to have over five divisors.\nWhat is the value of the first triangle number to have over five hundred divisors?";
            pb12display.DisplayHeader();

            //////////////////////////////////////////////////////////////////
            int solution = 500;
            long divisors = 1;
            long term = 1;
            long number = 1;

            while (divisors < solution)
            {
                number = Triangle.TriangleNumber(term);
                divisors = Triangle.NumberOfDivisors(number, solution);
                term++;
            }
            Console.WriteLine("value is " + number+" with " + divisors+ " divisors");

            // pb12display.DisplayAnswer("Prime number " + order + " is  :", result);

            pb12display.DisplayFooter();
            Console.ReadKey();
        }
    }
}
